import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/habitapp/generatedjournalwidget/generated/GeneratedHabbitWidget3.dart';
import 'package:flutterapp/habitapp/generatedjournalwidget/generated/GeneratedHabbitWidget4.dart';
import 'package:flutterapp/habitapp/generatedjournalwidget/generated/GeneratedTableviewRowWidget5.dart';
import 'package:flutterapp/habitapp/generatedjournalwidget/generated/GeneratedTabsWidget3.dart';
import 'package:flutterapp/habitapp/generatedjournalwidget/generated/GeneratedHabbitWidget2.dart';
import 'package:flutterapp/habitapp/generatedjournalwidget/generated/GeneratedHabbitWidget1.dart';
import 'package:flutterapp/habitapp/generatedjournalwidget/generated/GeneratedHabbitWidget.dart';
import 'package:flutterapp/habitapp/generatedjournalwidget/generated/GeneratedNavBarWidget1.dart';
import 'package:flutterapp/habitapp/generatedjournalwidget/generated/GeneratedTabBarWidget1.dart';
import 'package:flutterapp/habitapp/generatedjournalwidget/generated/GeneratedButtonsWidget23.dart';

/* Frame Journal
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedJournalWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 375.0,
              height: 812.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 220, 238, 231),
                      ),
                    ),
                    Positioned(
                      left: 0.0,
                      top: null,
                      right: 0.0,
                      bottom: -0.000030517578125,
                      width: null,
                      height: 83.00003051757812,
                      child: GeneratedTabBarWidget1(),
                    ),
                    Positioned(
                      left: null,
                      top: 0.0,
                      right: null,
                      bottom: null,
                      width: 375.0,
                      height: 139.0,
                      child: GeneratedNavBarWidget1(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 139.0,
                      right: null,
                      bottom: null,
                      width: 375.0,
                      height: 46.0,
                      child: GeneratedTabsWidget3(),
                    ),
                    Positioned(
                      left: 16.0,
                      top: 201.0,
                      right: null,
                      bottom: null,
                      width: 343.0,
                      height: 60.0,
                      child: GeneratedHabbitWidget(),
                    ),
                    Positioned(
                      left: 16.0,
                      top: 277.0,
                      right: null,
                      bottom: null,
                      width: 343.0,
                      height: 60.0,
                      child: GeneratedHabbitWidget1(),
                    ),
                    Positioned(
                      left: 16.0,
                      top: 353.0,
                      right: null,
                      bottom: null,
                      width: 343.0,
                      height: 60.0,
                      child: GeneratedHabbitWidget2(),
                    ),
                    Positioned(
                      left: 16.0,
                      top: 429.0,
                      right: null,
                      bottom: null,
                      width: 343.0,
                      height: 60.0,
                      child: GeneratedHabbitWidget3(),
                    ),
                    Positioned(
                      left: 16.0,
                      top: 553.0,
                      right: null,
                      bottom: null,
                      width: 343.0,
                      height: 60.0,
                      child: GeneratedHabbitWidget4(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 509.0,
                      right: 0.0,
                      bottom: null,
                      width: null,
                      height: 44.0,
                      child: GeneratedTableviewRowWidget5(),
                    )
                  ]),
            ),
            Positioned(
              left: 0.0,
              top: null,
              right: 0.0,
              bottom: 107.0,
              width: null,
              height: 50.0,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.13333333333333333;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.8026666666666666,
                      y: 0,
                      z: 0,
                      child: Container(
                        width: width,
                        child: GeneratedButtonsWidget23(),
                      ))
                ]);
              }),
            )
          ]),
    ));
  }
}
