import 'package:flutter/material.dart';
import 'package:flutterapp/habitapp/generatednewareawidget2/generated/GeneratedTabBarWidget2.dart';
import 'package:flutterapp/habitapp/generatednewareawidget2/generated/GeneratedTableviewRowWidget8.dart';
import 'package:flutterapp/habitapp/generatednewareawidget2/generated/GeneratedHabbitWidget6.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/habitapp/generatednewareawidget2/generated/GeneratedNavBarWidget2.dart';
import 'package:flutterapp/habitapp/generatednewareawidget2/generated/GeneratedHabbitWidget5.dart';
import 'package:flutterapp/habitapp/generatednewareawidget2/generated/GeneratedButtonsWidget30.dart';
import 'package:flutterapp/habitapp/generatednewareawidget2/generated/GeneratedTabsWidget5.dart';

/* Frame New Area
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedNewAreaWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 183, 222, 231),
                ),
              ),
              Positioned(
                left: 0.0,
                top: null,
                right: 0.0,
                bottom: -0.000030517578125,
                width: null,
                height: 83.00003051757812,
                child: GeneratedTabBarWidget2(),
              ),
              Positioned(
                left: null,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 139.0,
                child: GeneratedNavBarWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 139.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 46.0,
                child: GeneratedTabsWidget5(),
              ),
              Positioned(
                left: 0.0,
                top: null,
                right: 0.0,
                bottom: null,
                width: null,
                height: 50.0,
                child: TransformHelper.translate(
                    x: 0.00,
                    y: 274.00,
                    z: 0,
                    child: LayoutBuilder(builder:
                        (BuildContext context, BoxConstraints constraints) {
                      final double width =
                          constraints.maxWidth * 0.13333333333333333;

                      return Stack(children: [
                        TransformHelper.translate(
                            x: constraints.maxWidth * 0.8026666666666666,
                            y: 0,
                            z: 0,
                            child: Container(
                              width: width,
                              child: GeneratedButtonsWidget30(),
                            ))
                      ]);
                    })),
              ),
              Positioned(
                left: 16.0,
                top: 201.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 60.0,
                child: GeneratedHabbitWidget5(),
              ),
              Positioned(
                left: 16.0,
                top: 329.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 60.0,
                child: GeneratedHabbitWidget6(),
              ),
              Positioned(
                left: 0.0,
                top: 285.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 44.0,
                child: GeneratedTableviewRowWidget8(),
              )
            ]),
      ),
    ));
  }
}
