import 'package:flutter/material.dart';
import 'package:flutterapp/habitapp/generatedonboardingstp3widget/generated/GeneratedIndicatorWidget8.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/habitapp/generatedonboardingstp3widget/generated/GeneratedSystemBarWidget8.dart';
import 'package:flutterapp/habitapp/generatedonboardingstp3widget/generated/GeneratedFrameWidget2.dart';
import 'package:flutterapp/habitapp/generatedonboardingstp3widget/generated/GeneratedButtonsWidget62.dart';
import 'package:flutterapp/habitapp/generatedonboardingstp3widget/generated/GeneratedGroup3Widget2.dart';

/* Frame Onboarding stp 3
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedOnboardingstp3Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 375.0,
              height: 812.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 251, 240, 196),
                      ),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        final double width =
                            constraints.maxWidth * 0.8746666666666667;

                        final double height =
                            constraints.maxHeight * 0.35714285714285715;

                        return Stack(children: [
                          TransformHelper.translate(
                              x: constraints.maxWidth * 0.06133333333333333,
                              y: constraints.maxHeight * 0.6428571428571429,
                              z: 0,
                              child: Container(
                                width: width,
                                height: height,
                                child: GeneratedFrameWidget2(),
                              ))
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        final double width = constraints.maxWidth;

                        final double height =
                            constraints.maxHeight * 0.054187192118226604;

                        return Stack(children: [
                          TransformHelper.translate(
                              x: 0,
                              y: 0,
                              z: 0,
                              child: Container(
                                width: width,
                                height: height,
                                child: GeneratedSystemBarWidget8(),
                              ))
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        final double width = constraints.maxWidth * 0.872;

                        final double height =
                            constraints.maxHeight * 0.12192118226600986;

                        return Stack(children: [
                          TransformHelper.translate(
                              x: constraints.maxWidth * 0.064,
                              y: constraints.maxHeight * 0.22167487684729065,
                              z: 0,
                              child: Container(
                                width: width,
                                height: height,
                                child: GeneratedGroup3Widget2(),
                              ))
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        final double width = constraints.maxWidth * 0.872;

                        final double height =
                            constraints.maxHeight * 0.06157635467980296;

                        return Stack(children: [
                          TransformHelper.translate(
                              x: constraints.maxWidth * 0.064,
                              y: constraints.maxHeight * 0.4544334975369458,
                              z: 0,
                              child: Container(
                                width: width,
                                height: height,
                                child: GeneratedButtonsWidget62(),
                              ))
                        ]);
                      }),
                    )
                  ]),
            ),
            Positioned(
              left: 0.0,
              top: null,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: 31.748779296875,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.9615384114583333;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.01794871775309245,
                      y: 0,
                      z: 0,
                      child: Container(
                        width: width,
                        child: GeneratedIndicatorWidget8(),
                      ))
                ]);
              }),
            )
          ]),
    ));
  }
}
