import 'package:flutter/material.dart';
import 'package:flutterapp/habitapp/generatedaboutprojectwidget/generated/GeneratedDonwloadWidget.dart';
import 'package:flutterapp/habitapp/generatedaboutprojectwidget/generated/GeneratedLibrariesWidget.dart';
import 'package:flutterapp/habitapp/generatedaboutprojectwidget/generated/GeneratedCover1Widget.dart';
import 'package:flutterapp/habitapp/generatedaboutprojectwidget/generated/GeneratedIncreatinginterfacedesignfortheiOSplatformIuse2librarie.dart';
import 'package:flutterapp/habitapp/generatedaboutprojectwidget/generated/GeneratedAboutProjectWidget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/habitapp/generatedaboutprojectwidget/generated/GeneratedHabitisafreeandsimplehabitandmoodtrackerthathelpsyouorg.dart';
import 'package:flutterapp/habitapp/generatedaboutprojectwidget/generated/GeneratedCover2Widget.dart';
import 'package:flutterapp/habitapp/generatedaboutprojectwidget/generated/GeneratedDonwloadWidget1.dart';
import 'package:flutterapp/habitapp/generatedaboutprojectwidget/generated/GeneratedVector3Widget.dart';

/* Frame About Project
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAboutProjectWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 1024.0,
        height: 780.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 9, 14, 24),
                ),
              ),
              Positioned(
                left: 40.0,
                top: 100.0,
                right: null,
                bottom: null,
                width: 946.0,
                height: 63.0,
                child:
                    GeneratedHabitisafreeandsimplehabitandmoodtrackerthathelpsyouorg(),
              ),
              Positioned(
                left: 40.0,
                top: 261.0,
                right: null,
                bottom: null,
                width: 946.0,
                height: 180.0,
                child:
                    GeneratedIncreatinginterfacedesignfortheiOSplatformIuse2librarie(),
              ),
              Positioned(
                left: 40.0,
                top: 40.0,
                right: null,
                bottom: null,
                width: 781.0,
                height: 46.0,
                child: GeneratedAboutProjectWidget1(),
              ),
              Positioned(
                left: 40.0,
                top: 201.0,
                right: null,
                bottom: null,
                width: 781.0,
                height: 49.0,
                child: GeneratedLibrariesWidget(),
              ),
              Positioned(
                left: 40.0,
                top: 515.0,
                right: null,
                bottom: null,
                width: 461.0,
                height: 181.0,
                child: GeneratedCover1Widget(),
              ),
              Positioned(
                left: 523.0,
                top: 515.0,
                right: null,
                bottom: null,
                width: 461.0,
                height: 181.0,
                child: GeneratedCover2Widget(),
              ),
              Positioned(
                left: null,
                top: 712.0,
                right: null,
                bottom: null,
                width: 466.0,
                height: 33.0,
                child: TransformHelper.translate(
                    x: -239.00,
                    y: 0.00,
                    z: 0,
                    child: GeneratedDonwloadWidget()),
              ),
              Positioned(
                left: null,
                top: 712.0,
                right: null,
                bottom: null,
                width: 466.0,
                height: 33.0,
                child: TransformHelper.translate(
                    x: 244.00,
                    y: 0.00,
                    z: 0,
                    child: GeneratedDonwloadWidget1()),
              ),
              Positioned(
                left: 1024.0,
                top: 477.0,
                right: null,
                bottom: null,
                width: 0.0,
                height: 1043.0,
                child: GeneratedVector3Widget(),
              )
            ]),
      ),
    ));
  }
}
