import 'package:flutter/material.dart';
import 'package:flutterapp/habitapp/generatedcreatinghabitwidget/generated/GeneratedTableviewBatchWidget2.dart';
import 'package:flutterapp/habitapp/generatedcreatinghabitwidget/generated/GeneratedTableviewBatchWidget3.dart';
import 'package:flutterapp/habitapp/generatedcreatinghabitwidget/generated/GeneratedNavBarWidget4.dart';
import 'package:flutterapp/habitapp/generatedcreatinghabitwidget/generated/GeneratedKeyboardsWidget.dart';
import 'package:flutterapp/habitapp/generatedcreatinghabitwidget/generated/GeneratedTableviewBatchWidget.dart';
import 'package:flutterapp/habitapp/generatedcreatinghabitwidget/generated/GeneratedTableviewBatchWidget1.dart';

/* Frame Creating Habit
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCreatingHabitWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 243, 243, 243),
                ),
              ),
              Positioned(
                left: null,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 98.0,
                child: GeneratedNavBarWidget4(),
              ),
              Positioned(
                left: 16.0,
                top: 180.0,
                right: 16.0,
                bottom: null,
                width: null,
                height: 150.0,
                child: GeneratedTableviewBatchWidget(),
              ),
              Positioned(
                left: 16.0,
                top: 346.0,
                right: 16.0,
                bottom: null,
                width: null,
                height: 50.0,
                child: GeneratedTableviewBatchWidget1(),
              ),
              Positioned(
                left: 16.0,
                top: 412.0,
                right: 16.0,
                bottom: null,
                width: null,
                height: 50.0,
                child: GeneratedTableviewBatchWidget2(),
              ),
              Positioned(
                left: 16.0,
                top: 114.0,
                right: 16.0,
                bottom: null,
                width: null,
                height: 50.0,
                child: GeneratedTableviewBatchWidget3(),
              ),
              Positioned(
                left: 0.0,
                top: 522.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 290.0,
                child: GeneratedKeyboardsWidget(),
              )
            ]),
      ),
    ));
  }
}
