import 'package:flutter/material.dart';
import 'package:flutterapp/habitapp/generatedaddareawidget/generated/GeneratedEllipse3Widget.dart';
import 'package:flutterapp/habitapp/generatedaddareawidget/generated/GeneratedEllipse1Widget.dart';
import 'package:flutterapp/habitapp/generatedaddareawidget/generated/GeneratedTableviewBatchWidget5.dart';
import 'package:flutterapp/habitapp/generatedaddareawidget/generated/GeneratedEllipse4Widget.dart';
import 'package:flutterapp/habitapp/generatedaddareawidget/generated/GeneratedTableviewBatchWidget4.dart';
import 'package:flutterapp/habitapp/generatedaddareawidget/generated/GeneratedEllipse5Widget.dart';
import 'package:flutterapp/habitapp/generatedaddareawidget/generated/GeneratedNavBarWidget5.dart';
import 'package:flutterapp/habitapp/generatedaddareawidget/generated/GeneratedEllipse2Widget.dart';
import 'package:flutterapp/habitapp/generatedaddareawidget/generated/GeneratedTableviewBatchWidget6.dart';
import 'package:flutterapp/habitapp/generatedaddareawidget/generated/GeneratedKeyboardsWidget1.dart';

/* Frame Add Area
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAddAreaWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 243, 243, 243),
                ),
              ),
              Positioned(
                left: null,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 98.0,
                child: GeneratedNavBarWidget5(),
              ),
              Positioned(
                left: 16.0,
                top: 114.0,
                right: 16.0,
                bottom: null,
                width: null,
                height: 50.0,
                child: GeneratedTableviewBatchWidget4(),
              ),
              Positioned(
                left: 16.0,
                top: 180.0,
                right: 16.0,
                bottom: null,
                width: null,
                height: 190.0,
                child: GeneratedTableviewBatchWidget5(),
              ),
              Positioned(
                left: 16.0,
                top: 386.0,
                right: 16.0,
                bottom: null,
                width: null,
                height: 190.0,
                child: GeneratedTableviewBatchWidget6(),
              ),
              Positioned(
                left: 159.0,
                top: 281.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedEllipse1Widget(),
              ),
              Positioned(
                left: 199.0,
                top: 281.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedEllipse2Widget(),
              ),
              Positioned(
                left: 239.0,
                top: 281.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedEllipse3Widget(),
              ),
              Positioned(
                left: 279.0,
                top: 281.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedEllipse4Widget(),
              ),
              Positioned(
                left: 319.0,
                top: 281.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedEllipse5Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 522.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 290.0,
                child: GeneratedKeyboardsWidget1(),
              )
            ]),
      ),
    ));
  }
}
