import 'package:flutter/material.dart';
import 'package:flutterapp/habitapp/generatedcoverwidget/generated/GeneratedIPhone12ProWidget.dart';
import 'package:flutterapp/habitapp/generatedcoverwidget/generated/GeneratedRectangle7Widget.dart';
import 'package:flutterapp/habitapp/generatedcoverwidget/generated/GeneratedVector3Widget1.dart';
import 'package:flutterapp/habitapp/generatedcoverwidget/generated/GeneratedGroup192Widget.dart';
import 'package:flutterapp/habitapp/generatedcoverwidget/generated/GeneratedVector4Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/habitapp/generatedcoverwidget/generated/GeneratedTitleWidget106.dart';
import 'package:flutterapp/habitapp/generatedcoverwidget/generated/GeneratedIPhone12ProWidget4.dart';
import 'package:flutterapp/habitapp/generatedcoverwidget/generated/GeneratedVector6Widget.dart';
import 'package:flutterapp/habitapp/generatedcoverwidget/generated/GeneratedVector5Widget.dart';
import 'package:flutterapp/habitapp/generatedcoverwidget/generated/GeneratedFrame49Widget.dart';
import 'package:flutterapp/habitapp/generatedcoverwidget/generated/Generated26499902Widget1.dart';
import 'package:flutterapp/habitapp/generatedcoverwidget/generated/GeneratedTitleWidget107.dart';
import 'package:flutterapp/habitapp/generatedcoverwidget/generated/GeneratedGroup11Widget.dart';
import 'package:flutterapp/habitapp/generatedcoverwidget/generated/GeneratedGroup48Widget.dart';

/* Frame Cover
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCoverWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 1024.0,
        height: 512.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 9, 14, 24),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.3603515625;

                  final double height = constraints.maxHeight * 0.05078125;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.1513671875,
                        y: constraints.maxHeight * 0.244140625,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup48Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 573.0,
                top: 110.0,
                right: null,
                bottom: null,
                width: 0.0,
                height: 592.0,
                child: GeneratedVector3Widget1(),
              ),
              Positioned(
                left: 573.4998168945312,
                top: 631.5,
                right: null,
                bottom: null,
                width: 0.0,
                height: 1043.0,
                child: GeneratedVector5Widget(),
              ),
              Positioned(
                left: 104.49981689453125,
                top: 631.5,
                right: null,
                bottom: null,
                width: 0.0,
                height: 1043.0,
                child: GeneratedVector6Widget(),
              ),
              Positioned(
                left: 1024.0,
                top: 58.0,
                right: null,
                bottom: null,
                width: 0.0,
                height: 1043.0,
                child: GeneratedVector4Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.3603515625;

                  final double height = constraints.maxHeight * 0.30078125;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.1513671875,
                        y: constraints.maxHeight * 0.6484375,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedFrame49Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.3955078125;

                  final double height = constraints.maxHeight * 0.041015625;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.1513671875,
                        y: constraints.maxHeight * 0.591796875,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedTitleWidget106(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 155.0,
                top: 57.0,
                right: null,
                bottom: null,
                width: 54.0,
                height: 54.0,
                child: GeneratedGroup11Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.4994032084941864;

                  final double height =
                      constraints.maxHeight * 0.6842143535614014;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.5634765625,
                        y: constraints.maxHeight * 0.2421870231628418,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup192Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 609.0,
                top: 81.0,
                right: null,
                bottom: null,
                width: 255.0,
                height: 513.9534912109375,
                child: GeneratedIPhone12ProWidget(),
              ),
              Positioned(
                left: 897.0,
                top: 81.0,
                right: null,
                bottom: null,
                width: 255.0,
                height: 513.9534912109375,
                child: GeneratedIPhone12ProWidget4(),
              ),
              Positioned(
                left: 781.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 258.0,
                height: 512.0,
                child: GeneratedRectangle7Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.388671875;

                  final double height = constraints.maxHeight * 0.14453125;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.1513671875,
                        y: constraints.maxHeight * 0.443359375,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedTitleWidget107(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 1.1025390625;

                  final double height = constraints.maxHeight * 1.955078125;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * -0.1025390625,
                        y: constraints.maxHeight * -1.896484375,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: Generated26499902Widget1(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
