import 'package:flutter/material.dart';
import 'package:flutterapp/habitapp/generatedbannerwidget1/generated/GeneratedButtonWidget12.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/habitapp/generatedbannerwidget1/generated/GeneratedCheckmynewcasestudyWidget1.dart';
import 'package:flutterapp/habitapp/generatedbannerwidget1/generated/GeneratedBehance11Widget1.dart';

/* Instance Banner
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBannerWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(32.0),
      child: Container(
        width: 1024.0,
        height: 134.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(32.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(32.0),
                child: Container(
                  color: Color.fromARGB(255, 0, 87, 255),
                ),
              ),
              Positioned(
                left: 64.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 134.0,
                height: 134.0,
                child: GeneratedBehance11Widget1(),
              ),
              Positioned(
                left: null,
                top: 0.0,
                right: null,
                bottom: null,
                width: 1218.0,
                height: 136.0,
                child: TransformHelper.translate(
                    x: -2.00,
                    y: 0.00,
                    z: 0,
                    child: GeneratedCheckmynewcasestudyWidget1()),
              ),
              Positioned(
                left: null,
                top: 41.0,
                right: 34.0,
                bottom: null,
                width: 175.0,
                height: 56.0,
                child: GeneratedButtonWidget12(),
              )
            ]),
      ),
    ));
  }
}
